---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: github-instavote
  timeout: 1m0s
  url: https://github.com/AlbertGoma/LFS269-instavote-deploy.git
