apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- db-staging-helmrelease.yaml
#- github-instavote-provider.yaml
#- github-instavote-receiver.yaml
- instavote-gitrepository.yaml
#- lfs269-helmrepository.yaml
#- redis-staging-alert.yaml
- redis-staging-kustomization.yaml
#- result-staging-helmrelease.yaml
#- result-staging-image-policy.yaml
#- result-staging-image-repository.yaml
- slack-notif-alert.yaml
- slack-provider.yaml
#- vote-staging-alert.yaml
#- vote-staging-image-policy.yaml
#- vote-staging-image-repository.yaml
#- vote-staging-image-update.yaml
#- vote-staging-kustomization.yaml
#- worker-staging-alert.yaml
#- worker-staging-kustomization.yaml
