apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
namespace: instavote
images:
- name: schoolofdevops/vote
  newName: albertgoma/vote
  newTag: main-9def246b-1708508790 # {"$imagepolicy": "flux-system:vote:tag"}
replicas:
- name: vote
  count: 0
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
configMapGenerator:
- name: vote
  literals:
  - OPTION_A=FluxCD
  - OPTION_B=ArgoCD
